spring.application.name=hyban

spring.profiles.active=docker


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ybijoseph@gmail.com
spring.mail.password=Jq,h6!esFyXEmv_
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


server.port=7200

# Configuration CORS
#spring.web.cors.allowed-origins=http://localhost:7153,http://127.0.0.1:7153,http://192.168.1.6:7153,http://192.168.1.6:8080,http://127.0.0.1:3000,http://localhost:7200,http://127.0.0.1:7200,http://192.168.1.6:7200
#spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
#spring.web.cors.allowed-headers=*
#spring.web.cors.allow-credentials=true
#spring.web.cors.max-age=3600
