# DATABASE
spring.datasource.url=jdbc:postgresql://postgres-hrm:5432/hyban_db_v1
spring.datasource.username=directus
spring.datasource.password=directus

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# KEYCLOAK
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/hyban
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt.auth.converter.resource-id=hrm_frontend
jwt.auth.converter.principal-attribute=preferred_username

keycloak.admin.host=http://keycloak:8080
keycloak.admin.realm=hyban
keycloak.admin.clientId=keycloak-admin-client
keycloak.admin.clientSecret=${KEYCLOAK_CLIENT_SECRET}

# SERVER
server.port=7200

# UPLOAD
app.upload-dir=/app/uploads

# CORS
spring.web.cors.allowed-origins=http://localhost:7153,http://frontend:80
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

# MAIL
#spring.mail.host=${MAIL_HOST:smtp.gmail.com}
#spring.mail.port=${MAIL_PORT:587}
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}

# PERFORMANCE
spring.main.lazy-initialization=true
spring.jmx.enabled=false

# LOGGING
logging.level.root=INFO

# CARBONE
#carbone.url=http://carbone:4000/render