spring.datasource.url=jdbc:postgresql://localhost:5432/hyban_db_v1
spring.datasource.username=directus
spring.datasource.password=directus
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
spring.jpa.hibernate.ddl-auto=update


app.upload-dir=/uploads/documents

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.profiles.active=dev

##Keycloak config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.1.5:8080/realms/hyban
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt.auth.converter.resource-id=hrm_frontend
jwt.auth.converter.principal-attribute=preferred_username

## keycloak admin settings
keycloak.admin.host=http://192.168.1.5:8080
keycloak.admin.realm=hyban
keycloak.admin.clientId=keycloak-admin-client
keycloak.admin.clientSecret=b6cFLwyL2MakdzHxomjsamxesop9IbIE
#keycloak.admin.clientUUID=ef90c853-2e73-4ebe-8d8f-a46aa7211789



carbone.url=http://localhost:4000/render

#swagger-ui config
springdoc.show-actuator=true
# Disabling the /v3/api-docs endpoint
springdoc.api-docs.enabled=true
# Disabling the swagger-ui
springdoc.swagger-ui.enabled=true





logging.level.root=INFO


server.port=7200
