

spring.datasource.url=jdbc:postgresql://localhost:5432/hybanBD
spring.datasource.username=directus
spring.datasource.password=directus
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG

spring.mvc.view.prefix=/WEB-INF/views/jsp
spring.mvc.view.suffix=.jsp
spring.thymeleaf.enabled=false

spring.mvc.static-path-pattern=/static/**
spring.resources.static-locations=classpath:/static/

report.path=src/main/resources/reports/

logging.level.root=INFO


app.upload-dir=uploads/documents

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

server.port=7100

#swagger-ui config - Activer Swagger sans authentification
springdoc.show-actuator=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Désactiver la sécurité OAuth2 pour le développement
# spring.security.oauth2.resourceserver.jwt.issuer-uri=
# spring.security.oauth2.resourceserver.jwt.jwk-set-uri=

# Configuration CORS pour Swagger
spring.web.cors.allowed-origins=http://localhost:7100,http://192.168.1.5:7100,http://localhost:7200,http://localhost:4200,http://127.0.0.1:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
spring.web.cors.max-age=3600
